id: PAAA93D91
initial_creation_type: ocr
source_metadata:
  volumes:
    54f354f7d1174bdf96a3bc7ed796f14f:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
